### ISSUE TITLE
Unhandled Runtime Error: Hydration failed because the initial UI does not match what was rendered on the server.

### ISSUE THREAD

**Issue by waveflip** [TomasGonzalez/hand-gesture-recognition-using-mediapipe-in-react#1]
Hi, I'm encountering a few errors when trying to run your code here, not sure why.

```
Unhandled Runtime Error
Error: Hydration failed because the initial UI does not match what was rendered on the server.
See more info here: https://nextjs.org/docs/messages/react-hydration-error
```

```
Unhandled Runtime Error
Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.
```

Steps to reproduce:
1. Clone this repo
2. npm install
3. npm run dev

From what I can tell, a react-hydration-error can occur due to invalid markup (for instance, a div tag inside a p tag). But since you show examples of your code working in the README, I assume this wasn't an issue for you. Maybe I'm missing something obvious? Any help is appreciated, thanks

**Comment by TomasGonzalez** [comment]
Hi, 
I'll dedicate some time to fix it, tnks for bringing it up.

**Comment by TomasGonzalez** [comment]
@waveflip I migrated the repo to Vite, it's now working just fine.
