### ISSUE TITLE
How to convert to TFJS model?

### ISSUE THREAD

**Issue by eshanrajapakshe** [TomasGonzalez/hand-gesture-recognition-using-mediapipe-in-react#2]
How did you convert the `keypoint_classifier.hdf5` file to .json model? What script did you use?
I tried this. Didn't work.

`tensorflowjs_converter --input_format=tf_saved_model --output_node_names='detection_boxes,detection_classes,detection_features,detection_multiclass_scores,detection_scores,num_detections,raw_detection_boxes,raw_detection_scores' --output_format=tfjs_graph_model --signature_name=serving_default 'model/keypoint_classifier/ /converted`

**Comment by eshanrajapakshe** [comment]
Found this code and was able to convert it

`tensorflowjs_converter --input_format keras --output_format tfjs_graph_model model/keypoint_classifier/keypoint_classifier.hdf5 tfjs_model/`

**Comment by TomasGonzalez** [comment]
Nice, thanks for sharing it. I had forgotten this. I you want you can add it to the readme and make a PR.
